BEGIN { $ENV{ATRIA_FORCE_GUI} = 1 unless exists $ENV{ATRIA_FORCE_GUI} }
use ClearCase::ClearPrompt qw(+STDERR +WARN +DIE),
				'+DIE=' . ($ENV{LOGNAME} || $ENV{USERNAME});

warn qq(This is a warning\n);		# explicit warning from this process
system q(perl nosuchscript);		# error msg generated by child process
die qq(This is a fatal error);		# explict error msg from this process,
					# should be "dialoged" AND emailed.
print "didn't die!!!\n";		# we should not get here
