BEGIN { $ENV{ATRIA_FORCE_GUI} = 1 unless exists $ENV{ATRIA_FORCE_GUI} }
use ClearCase::ClearPrompt qw(+STDERR +WARN +DIE);
warn qq(This is a warning\n);		# explicit warning from this process
system q(perl nosuchscript);		# error msg generated by child process
die qq(This is a fatal error);		# explict error msg from this process
print "didn't die!!!\n";		# should not get here
